### ISSUE TITLE
how the dismiss is supposed to work? 

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_cookieconsent#15]
hi
sorry for the maybe dummy question, but how the dismiss the informationnal message is supposed to work?

I was thinking that I will have the message until I dismiss the message, wherever I ma on my website.
I fact, it is dismissed when I start to visit my site (it is on the first page, and disapear on the 2nd one)

**Comment by acrylian** [comment]
Not sure what you mean exaclty. You get that overlay somewhere until you click it away (= dismiss it). The script then sets a cookie that you did dismiss it and should not show it again. Until the cookie is delete or reached its end of live time (don't remember which that is but quite long).

**Comment by vincent3569** [comment]
I have some other tests, with ff and ie and It seems to work as described.

I have few other questions:
- how option 'zpcookieconsent_dismissonscroll' is supposed to work ?
when I enable this option, it has no effect, when I naviguate on my site or when I scroll a page of my site.

- as option 'zpcookieconsent_scrollrange' is removed, this text of option 'zpcookieconsent_dismissonscroll' is unexpected: 'The scroll range option must be set.'
