### ISSUE TITLE
deny button useless with the default compliance option 'info'

### ISSUE THREAD

**Issue by vincent3569** [acrylian/zp_cookieconsent#17]
hi

as far I can see, the default compliance value of cookieconsent is 'info':
https://cookieconsent.insites.com/documentation/javascript-api/

with that default value, unchanged by the plugin, 'decline' infos (decline button and content data) are useless.

so, these code lines shoult be removed:
````
				gettext_pl('Button: Decline', 'zp_cookieconsent') => array(
						'key' => 'zpcookieconsent_buttondecline',
						'type' => OPTION_TYPE_TEXTBOX,
						'order' => 3,
						'desc' => gettext_pl('Link text for the decline button', 'zp_cookieconsent')),
````

and 

````
		$decline = gettext_pl('Decline', 'zp_cookieconsent');
		if (getOption('zpcookieconsent_buttondecline')) {
			$decline = get_language_string(getOption('zpcookieconsent_buttondecline'));
		}
````

and 

````
						"deny": "<?php echo js_encode($decline); ?>",
````

**Comment by acrylian** [comment]
It follows the part here on the same page you linked: 
![bildschirmfoto 2018-05-17 um 10 32 04](https://user-images.githubusercontent.com/2474309/40165941-9261f2c2-59bd-11e8-8cae-2d16bca00c71.jpg)

**Comment by acrylian** [comment]
Okay, I see, apparently missed the from their script update. Should we maybe include that `type` option instead?

**Comment by vincent3569** [comment]
that is, of course, another way to solve the issue :-)
'info' seems to be enough for my personnal needs, but why not include 'opt-in' and 'opt-out' values.

**Comment by acrylian** [comment]
For me it is enough, too. But who knows what come with the GDPR and opt-in is required for a lot of other things. (even if it is all annoying and kind of breaking a butterfly on a wheel regarding cookies in general…but we don't make those rules…)
