### ISSUE TITLE
typo in plugin name beside some gettext_pl strings

### ISSUE THREAD

**Issue by bic-ed** [acrylian/zp_cookieconsent#5]
i.e. on line 44
`'desc' => gettext_pl('Link to your cookie policy / privacy info page.', 'zpCookieconsent')),`
 should be
`'desc' => gettext_pl('Link to your cookie policy / privacy info page.', 'zp_cookieconsent')),`

I also see the need of adding `'multilingual' => 1,` to some `OPTION_TYPE_TEXTBOX` options.

**Comment by acrylian** [comment]
Thanks and sorry again!
