### ISSUE TITLE
missing NONE option for themes and misleading description

### ISSUE THREAD

**Issue by bic-ed** [acrylian/zp_cookieconsent#7]
The description of theme option says 

> Select NONE to use your own css via your custom theme for example.

 Actually is not possible to "select NONE", instead it's possible to select "custom", but then a file named "custom.css" must be added by the user in `styles` folder.

**Comment by acrylian** [comment]
Yeah, you are right, "none" is the wrong wording and actually selecting "custom" should not load any css at all since the theme's css is meant to take over everything.

**Comment by bic-ed** [comment]
I suggest to have both options. At the moment I'm experimenting with my custom.css file. But we don't need to add it to the package, we just need to clearly say that who wants to use a custom css must add it to the style folder.

I didn't say yet, but I wanted to add a conditional loading to the whole banner code, so that if the cookie is already present nothing is uselessly added to the html. Then it make sense not to insert the (eventual) custom css code in the main theme css, using instead a small custom css file, loaded just the first time an user visit the site.

I can add all of this in the pull request I'm working on.

**Comment by acrylian** [comment]
Makes sense. And I like the idea of not loading anything if not needed. A cookie check is probably easy via the available ZP cookie functions so we can just skip the filter assignment loading everything.

**Comment by bic-ed** [comment]
Yes, I don't remember the zenphoto function, I just wrote a code like this:
`if(!isset($_COOKIE['cookieconsent_dismissed'])) {
zp_register_filter('theme_body_close', 'zpCookieconsent::getJS');
}`

**Comment by bic-ed** [comment]
Also, it might be nice to have the selector menu build automatically, picking the css files present in the style folder (plus, eventually, an empty selector, the NONE one). I should study how to do it but probably you can do it in minutes.

**Comment by acrylian** [comment]
We have functions like `zp_getCookie()` but since we don't use the content the simple check will do as well.

Sure I could also add something to get the styles directory but not sure if that is really needed. This should have been just a simple plugin for this rather silly legal requirement ;-)

**Comment by bic-ed** [comment]
I'm afraid we have to remove the option "none". With your latest commit, the script falls back to its default theme when "none" is selected. Actually, only with a missing css file it might be possible to stylize the banner from the global theme css, just because it broke somehow the script.
I'm ready with the pull request. If it's ok for you I can include the removing of "none" option.

**Comment by bic-ed** [comment]
There are also too many multilingual options now, for instance "Expire". May be "Domain" and "Button: Learn more - Link" too?

**Comment by acrylian** [comment]
Ah, I had a far memory that it uses the default if no css is set. Or maybe the option from the script  define needs to be remove. Yes, sure, include the removal of the "none" option.

Thanks for the note about the multilingual defines… My fault doing the last update too quickly inbetween doing other things…

**Comment by bic-ed** [comment]
Then I remove also all of those 3 multilingual?

**Comment by acrylian** [comment]
Sure, while you are already at it ;-) Thanks!

**Comment by bic-ed** [comment]
ok

**Comment by acrylian** [comment]
Guess I can close this ;-)
